//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bike_Shop_Đir
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPOVI_ZAPOSLENIKA
    {
        public TIPOVI_ZAPOSLENIKA()
        {
            this.ZAPOSLENICIs = new HashSet<ZAPOSLENICI>();
        }
    
        public int tip_zaposlenika_id { get; set; }
        public string tip_zaposlenika { get; set; }
    
        public virtual ICollection<ZAPOSLENICI> ZAPOSLENICIs { get; set; }
    }
}
