//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bike_Shop_Đir
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPOVI_TURA
    {
        public TIPOVI_TURA()
        {
            this.KATALOG_TURA = new HashSet<KATALOG_TURA>();
        }
    
        public int tip_ture_id { get; set; }
        public string naziv_tipa_ture { get; set; }
    
        public virtual ICollection<KATALOG_TURA> KATALOG_TURA { get; set; }
    }
}
