//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bike_Shop_Đir
{
    using System;
    using System.Collections.Generic;
    
    public partial class KOMPONENTE
    {
        public KOMPONENTE()
        {
            this.KATALOG_DIJELOVA = new HashSet<KATALOG_DIJELOVA>();
        }
    
        public int komponenta_id { get; set; }
        public string naziv_komponente { get; set; }
        public byte[] slika_komponente { get; set; }
    
        public virtual ICollection<KATALOG_DIJELOVA> KATALOG_DIJELOVA { get; set; }
    }
}
