//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bike_Shop_Đir
{
    using System;
    using System.Collections.Generic;
    
    public partial class KORPE
    {
        public int korpa_id { get; set; }
        public Nullable<int> klijent_id { get; set; }
        public Nullable<double> ukupna_cijena { get; set; }
        public Nullable<System.DateTime> vrijeme_kupovine { get; set; }
        public Nullable<int> broj_stavki { get; set; }
        public Nullable<int> stavka_id { get; set; }
    
        public virtual KLIJENTI KLIJENTI { get; set; }
        public virtual STAVKE_KORPE STAVKE_KORPE { get; set; }
    }
}
