//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bike_Shop_Đir
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPOVI_BICIKALA
    {
        public TIPOVI_BICIKALA()
        {
            this.KATALOG_BICIKALA = new HashSet<KATALOG_BICIKALA>();
        }
    
        public int tip_bicikla_id { get; set; }
        public string naziv_tipa { get; set; }
    
        public virtual ICollection<KATALOG_BICIKALA> KATALOG_BICIKALA { get; set; }
    }
}
